version: 0.2
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
      - apk add --update 'py-pip'
      - pip install 'docker-compose==1.9.0'
  pre_build:
    commands:
      - cp env.sample .env
      - docker-compose -f docker-compose-test.yml build
  build:
    commands:
      - docker-compose -f docker-compose-test.yml up -d postgres
      - sleep 5 # give postgres enough time to wake up. TODO: race condition...
      - docker-compose -f docker-compose-test.yml run rails /bin/bash -c 'cd /app; build-scripts/main.sh'
