version: '2'
services:
  rails:
    ports:
      - '3000:3000'
      - '8080:8080'
    volumes:
      - .:/app
    build:
      dockerfile: docker/odyssey/Dockerfile.devel
      context: .
    env_file: .env

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=secretsecret
