version: '2'
services:
  rails:
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    build:
      dockerfile: docker/odyssey/Dockerfile.devel
      context: .

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=secretsecret
