version: '2'
services:
  rails:
    volumes:
      - .:/app
    build:
      dockerfile: docker/odyssey/Dockerfile.devel
      context: .
    env_file: .env

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secretsecret
