FROM ruby:2.4.2

RUN apt-get update

# install latest node
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs


# install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - 
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list 

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y yarn

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
